# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-ContentExtractor
version:      0.01
version_from: lib/HTML/ContentExtractor.pm
installdirs:  site
requires:
    HTML::TreeBuilder:             1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
